name: CI/CD Pipeline

on:    - name: Run tests with coverage
      run: mvn clean test jacoco:report -Dmaven.test.failure.ignore=true
      continue-on-error: true

    - name: Display Coverage Results
      run: |
        echo " COVERAGE REPORT SUMMARY "
        echo "================================"
        if [ -f target/site/jacoco/index.html ]; then
          # Extract coverage percentage from JaCoCo HTML report
          COVERAGE=$(grep -o '<td class="ctr2" id="c[0-9]*">[0-9]*%</td>' target/site/jacoco/index.html | head -1 | grep -o '[0-9]*%' || echo "N/A")
          echo "🎯 TOTAL COVERAGE: $COVERAGE"
          echo "✅ Target: 60% minimum"
          if [ -f target/site/jacoco/jacoco.xml ]; then
            # Try to get more detailed info from XML
            LINES_COVERED=$(grep -o 'covered="[0-9]*"' target/site/jacoco/jacoco.xml | head -1 | grep -o '[0-9]*' || echo "0")
            LINES_MISSED=$(grep -o 'missed="[0-9]*"' target/site/jacoco/jacoco.xml | head -1 | grep -o '[0-9]*' || echo "0")
            if [ "$LINES_COVERED" != "0" ] && [ "$LINES_MISSED" != "0" ]; then
              TOTAL_LINES=$((LINES_COVERED + LINES_MISSED))
              echo " covered: $LINES_COVERED / $TOTAL_LINES"
            fi
          fi
          echo "Coverage report generated successfully!"
        else
          echo " Coverage report not found"
        fi
        echo "================================"h:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  test:
    name: Run Tests and Code Coverage
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        cache: maven

    - name: Run tests with coverage
      run: mvn clean test jacoco:report -Dmaven.test.failure.ignore=true
      continue-on-error: true

    - name: Coverage report generated
      run: echo "Tests executed and coverage report generated successfully"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./target/site/jacoco/jacoco.xml
        fail_ci_if_error: false

    - name: Comment coverage on PR
      if: github.event_name == 'pull_request'
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 60
        min-coverage-changed-files: 60

  build:
    name: Build Application
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        cache: maven

    - name: Build application
      run: mvn clean package -DskipTests

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jar-file
        path: target/*.jar
        retention-days: 1